// <auto-generated />
using System;
using MenuRestaurantWebAPP.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MenuRestaurantWebAPP.Contexts.Migrations
{
    [DbContext(typeof(MenuRestaurantDbContext))]
    partial class MenuRestaurantDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MenuRestaurantWebAPP.Models.Pietanza", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PortataId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Prezzo")
                        .HasColumnType("float");

                    b.Property<string>("Tipologia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PortataId");

                    b.ToTable("_pietanze");
                });

            modelBuilder.Entity("MenuRestaurantWebAPP.Models.Portata", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Tipologia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("_portate");
                });

            modelBuilder.Entity("MenuRestaurantWebAPP.Models.Pietanza", b =>
                {
                    b.HasOne("MenuRestaurantWebAPP.Models.Portata", null)
                        .WithMany()
                        .HasForeignKey("PortataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
